SOLVER:
  BASE_LR: 0.0001
  BATCHSIZE: 16
  NUM_WORKERS: 4
  WEIGHT_DECAY: 0.0001
  LR_STEP_SIZE: 20
  LR_GAMMA: 0.1
  EPOCH: 25
  SAVE_INTERVAL: 1
LOSS:
  TYPE: 'silog_loss_variance'
  W_depth_final: 1.0
  DEPTH_INIT: 'silog_loss_variance'
  W_depth_init: 0.5
  DEPTH_OFFSET: 'silog_loss_variance'
  W_depth_offset: 0.5
  SSIM: False # make sure depth_offset loss is defined
  W_depth_SSIM: 0.5
  ONLY_COMPLETED_DEPTH_SUPERVISION: False
  PQRS: 'l1_pqrs' # PQRS options: plane_pqrs, l1_pqrs
  NU: 1.0
  KSI: 1.0
  MULTISCALE: ''
  SMOOTH: ''
  LAMBDA: 1.0
  PATCH: 'patch_approx'
  PATCH_SIZE: 32
  RHO: 1.0
SEED: 1
TEST:
  BATCHSIZE: 1
  SAVE_RESULTS: False
  SAVE_POINTCLOUDS: False
  SAVE_PQRS: FALSE
  SAVE_OFFSETS_CONFIDENCE: FALSE
DEVICE: 'cuda'
CMAP: 'rainbow'
OUTPUT_DIR: 'output/'
RESUME: ''
#eigin gt and depth completed no convert L yes!
#CKPT_PATH: 'output/StructRankNetPQRS_resnet101_19_09_2022-144559_default_KITTI_eigen/KITTI_eigen/3m8ya5fi/checkpoints/epoch=023-rmse=3.780-delta1=0.896.ckpt'
#add loss
CKPT_PATH: 'output/StructRankNetPQRS_resnet101_23_09_2022-091726_default_KITTI_eigen/KITTI_eigen/37gz0bzw/checkpoints/epoch=021-rmse=3.590-delta1=0.904.ckpt'
